spring:
  config:
    activate:
      on-profile: local-h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
  cloud:
    aws:
      credentials:
        access-key: ????
        secret-key: ????
      region:
        static: ap-northeast-2
      stack:
        auto: false
      sns:
        topic:
          arn: arn:aws:sns:ap-northeast-2:533267093729:dev-domain-event-all-in-one.fifo:9ad70b95-80f2-482c-a077-0140bb113eb2
      sqs:
        queue:
          name: dev-domain-event-all-in-one.fifo